# Generated by Django 5.0.7 on 2024-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_photo', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
