# Generated by Django 5.0.7 on 2024-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_userpost_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='Знак публикации'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
