# Generated by Django 5.0.7 on 2024-08-20 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userpost_creation_date_userpost_publication_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 54, 38, 982881), verbose_name='Дата создания'),
        ),
    ]
