# Generated by Django 5.0.7 on 2024-08-20 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userpost_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 55, 8, 735509), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='publication_sign',
            field=models.BooleanField(default=False, verbose_name='Знак публикации'),
        ),
    ]
