# Generated by Django 5.0.7 on 2024-09-02 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_userpost_creation_date_alter_userpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 18, 30, 35, 855472), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='blog_picture/', verbose_name='Картинка'),
        ),
    ]
