# Generated by Django 5.0.7 on 2024-09-02 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_userpost_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 20, 27, 14, 267644), verbose_name='Дата создания'),
        ),
    ]
