# Generated by Django 5.0.7 on 2024-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_userpost_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
