# Generated by Django 5.0.7 on 2024-09-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_publication', 'can_change_publication'), ('can_change_description', 'can_change_description'), ('can_change_category', 'can_change_category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
